# Generated by Django 5.0.2 on 2024-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='Paragraph',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
