# Generated by Django 5.0.2 on 2024-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=50)),
                ('projects', models.CharField(max_length=50)),
                ('hours_of_support', models.CharField(max_length=50)),
                ('workers', models.CharField(max_length=50)),
            ],
        ),
    ]
