# Generated by Django 5.0.2 on 2024-08-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_headling_aboutus_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
