# Generated by Django 5.0.2 on 2024-08-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='headline',
            field=models.CharField(default='default headline', max_length=250),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
