# Generated by Django 5.0.2 on 2024-08-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feature_headline_alter_feature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('quote', models.CharField(max_length=250)),
            ],
        ),
    ]
