# Generated by Django 5.0.2 on 2024-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(),
        ),
    ]
